# Generated by Django 4.1.1 on 2023-03-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('salary', models.IntegerField()),
                ('details', models.TextField()),
                ('abalable', models.BooleanField()),
                ('catagory', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=50)),
                ('middle', multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('Englidh', 'English'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='Bangla', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='media/images/')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
