# Generated by Django 4.1.1 on 2023-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post_model',
            name='student',
            field=models.ManyToManyField(related_name='set_student', to='post.student'),
        ),
        migrations.AddField(
            model_name='post_model',
            name='teacher',
            field=models.ManyToManyField(related_name='set_teacher', to='post.teacher'),
        ),
    ]
