# Generated by Django 4.1.1 on 2023-03-23 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_student_teacher_post_model_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='user',
        ),
        migrations.AddField(
            model_name='post_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
