# Generated by Django 4.1.1 on 2023-04-01 10:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_model_user_post_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='middle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='Bangla', max_length=50),
        ),
    ]
