# Generated by Django 4.1.1 on 2023-04-05 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_post_model_likes_post_model_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='likes',
            field=models.ManyToManyField(related_name='set_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
