# Generated by Django 4.1.1 on 2023-05-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_picaddmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='picaddmodel',
            new_name='photo_add_model',
        ),
    ]
