# Generated by Django 4.1.1 on 2023-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_picaddmodel_photo_add_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post_model',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
