# Generated by Django 4.1.1 on 2023-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_district_post_model_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='catagory',
            field=models.CharField(choices=[('Subject', 'Subject'), ('Class_in', 'Class_in')], max_length=50),
        ),
    ]
