# Generated by Django 4.1.1 on 2023-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_model_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='catagory',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=50),
        ),
    ]
