# Generated by Django 4.1.1 on 2023-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
