# Generated by Django 4.1.1 on 2023-05-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_alter_post_model_catagory'),
        ('profileapp', '0002_alter_userprofile_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', multiselectfield.db.fields.MultiSelectField(choices=[('Group_Tuition', 'Group_Tuition'), ('Private_Tuition', 'Private_Tuition')], max_length=50)),
                ('place', multiselectfield.db.fields.MultiSelectField(choices=[('Class_rooms', 'Class_rooms'), ('Coaching_center', 'Coaching_center'), ('Home_visit', 'Home_visit'), ('My_place', 'My_place')], max_length=50)),
                ('aproach', multiselectfield.db.fields.MultiSelectField(choices=[('Online_help', 'Online_help'), ('Phone_help', 'Phone_hlep'), ('Provide_Hand_Notes', 'Provide_Hand_Notes'), ('Video_Tutorials', 'Video_Tutorials')], max_length=50)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('Bangla_medium', 'Bangla_medium'), ('English_medium', 'English_medium'), ('Arabic_medium', 'Arabic_medium'), ('Hindi_medium', 'Hindi_medium'), ('China_medium', 'China_medium'), ('Computer learning', 'Computer_learning'), ('Language learning', 'Language_learning')], max_length=50)),
                ('salary', models.IntegerField(max_length=50)),
                ('days_per_week', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('statas', models.CharField(choices=[('Available', 'Available'), ('busy', 'busy')], max_length=50)),
                ('class_in', models.ManyToManyField(related_name='students', to='post.student')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='post.district')),
                ('subject', models.ManyToManyField(related_name='teachers', to='post.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
