# Generated by Django 4.1.1 on 2023-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_teacher_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_model',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
