# Generated by Django 4.1.1 on 2023-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_model_catagory'),
        ('profileapp', '0005_alter_teacher_model_class_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_model',
            name='class_in',
            field=models.ManyToManyField(related_name='set_class_in', to='post.student'),
        ),
        migrations.AlterField(
            model_name='teacher_model',
            name='subject',
            field=models.ManyToManyField(related_name='set_subject', to='post.teacher'),
        ),
    ]
