# Generated by Django 4.1.1 on 2023-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_alter_teacher_model_class_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_model',
            name='class_in',
            field=models.ManyToManyField(related_name='set_class_in', to='profileapp.class_in'),
        ),
        migrations.AlterField(
            model_name='teacher_model',
            name='subject',
            field=models.ManyToManyField(related_name='set_subject', to='profileapp.subject'),
        ),
    ]
