# Generated by Django 4.1.1 on 2023-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_class_in_subject_alter_teacher_model_class_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_model',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher_model',
            name='subject_in',
            field=models.ManyToManyField(related_name='set_subject_in', to='profileapp.subject'),
        ),
    ]
