# Generated by Django 4.1.1 on 2023-05-30 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0008_remove_teacher_model_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
